spring:
  application:
    name: taco-cloud
  data:
    cassandra:
      keyspace-name: taco_cloud
      schema-action: create-if-not-exists
      local-datacenter: datacenter1
      contact-points: 127.0.0.1
      port: 9042
      request:
        timeout: 10s