spring:
  data:
    rest:
      base-path: /data-api
  application:
    name: taco-cloud #Название приложения
  datasource:
    schema: #Источник данных - схема
      - schema.sql
    data: # Источник данных - данные
      - data.sql
    url: jdbc:h2:mem:tacocloud # URL БД
    driver-class-name: org.h2.Driver # драйвер СУБД
    username: tacouser # пользователь БД
    password: tacopassword # пароль БД
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "https://localhost:8443/login/oauth2/code/google"
# Для генерации ssl ключей используем:
# keytool -keystore mykeys.jks -genkey -alias tomcat -keyalg RSA
server:
  port: 8443
  ssl:
    key-store: ${KEY_STORE_PATH}
    #file:/home/hotking/keys/mykeys.jks
    key-store-password: ${KEY_STORE_PASSWORD}
    key-password: ${KEY_STORE_PASSWORD}
taco:
  orders:
    page-size: 10
logging:
  level:
    root: warn

---

spring:
  config:
    activate:
      on-profile: test
logging:
  level:
    root: debug

---

spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    root: info

---

spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    root: info