spring:
  data:
    rest:
      base-path: /data-api
  application:
    name: taco-cloud #Название приложения
  datasource:
    schema: #Источник данных - схема
      - schema.sql
    data: # Источник данных - данные
      - data.sql
    url: jdbc:h2:mem:tacocloud # URL БД
    driver-class-name: org.h2.Driver # драйвер СУБД
    username: tacouser # пользователь БД
    password: tacopassword # пароль БД
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
      client:
        registration:
          taco-admin-client:
            provider: tacocloud
            client-id: taco-admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "https://127.0.0.1:8443/login/oauth2/code/{registrationId}"
            scope: writeIngredients,deleteIngredients,openid
        provider:
          tacocloud:
#            issuer-uri: http://127.0.0.1:9000
            authorization-uri: http://127.0.0.1:9000/oauth2/authorize
            token-uri: http://127.0.0.1:9000/oauth2/token
            jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks
            user-name-attribute: sub
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "https://127.0.0.1:8443/login/oauth2/code/google"
# Для генерации ssl ключей используем:
# keytool -keystore mykeys.jks -genkey -alias tomcat -keyalg RSA
server:
  port: 8443
  ssl:
    key-store: ${KEY_STORE_PATH}
    #file:/home/hotking/keys/mykeys.jks
    key-store-password: ${KEY_STORE_PASSWORD}
    key-password: ${KEY_STORE_PASSWORD}
taco:
  orders:
    page-size: 10
logging:
  level:
    root: warn

---

spring:
  config:
    activate:
      on-profile: test
logging:
  level:
    root: debug

---

spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    root: info

---

spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    root: info